site_name: Berlingo
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.ico
  palette:
    primary: '#93d333'
    accent: '#ffc700'
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - include-markdown:
      encoding: utf-8

markdown_extensions:
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
  - pymdownx.details

repo_url: https://github.com/berlingoextension/berlingo
repo_name: Source code

extra_css:
  - assets/custom.css

nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Get started: get-started.md
  - FAQ: faq.md
  - Changelog: changelog.md